server:
  port: 9091

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8094/eureka}
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

spring:
  application:
    name: ms-gateway-server

  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
          routes:
            - id: ms-catalogo
              uri: lb://ms-catalogo
              predicates:
                - Path=/categoria/**
            - id: ms-producto
              uri: lb://ms-producto
              predicates:
                - Path=/producto/**
            - id: ms-matricula
              uri: lb://ms-matricula
              predicates:
                - Path=/matriculas/**
            - id: ms-curso
              uri: lb://ms-curso
              predicates:
                - Path=/cursos/**

              # Si tu servicio real no expone /categoria/...:
              # filters:
              #   - StripPrefix=1
