spring:
  application:
    name: ms-matricula

  datasource:
    url: jdbc:postgresql://localhost:3306/ms_matricula
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect



server:
  port: 7569


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8094/eureka
  instance:
    hostname: localhost
